import withField from './withField';
import Input from '../input/Input';
import TextArea from '../input/TextArea';
import InputNumber from '../inputNumber/InputNumber';
import Select from '../select/Select';
import { Checkbox, CheckboxGroup } from '../checkbox';
import { Radio, RadioGroup } from '../radio';
import DatePicker from '../datePicker';
import Switch from '../switch';
import Slider from '../slider';
import TimePicker from '../timePicker';
import TreeSelect from '../treeSelect';
import Cascader from '../cascader';
import Rating from '../rating';
import AutoComplete from '../autoComplete';
import Upload from '../upload';
import TagInput from '../tagInput';
import PinCode from '../pincode';

export const FormInput = withField(Input, { maintainCursor: true });
export const FormInputNumber = withField(InputNumber, { maintainCursor: true });
export const FormTextArea = withField(TextArea, { maintainCursor: true });
export const FormSelect = withField(Select);
(FormSelect as any).Option = (Select as any).Option;
(FormSelect as any).OptGroup = (Select as any).OptGroup;
export const FormCheckboxGroup = withField(CheckboxGroup);
export const FormCheckbox = withField(Checkbox, { valueKey: 'checked', valuePath: 'target.checked', shouldInject: false });
export const FormRadioGroup = withField(RadioGroup, { valuePath: 'target.value' });
export const FormRadio = withField(Radio, { valueKey: 'checked', valuePath: 'target.checked', shouldInject: false });
export const FormDatePicker = withField(DatePicker);
export const FormSwitch = withField(Switch, { valueKey: 'checked' });
export const FormSlider = withField(Slider);
export const FormTimePicker = withField(TimePicker);
export const FormTreeSelect = withField(TreeSelect);
export const FormCascader = withField(Cascader);
export const FormRating = withField(Rating);
export const FormAutoComplete = withField(AutoComplete, { valueKey: 'value', onKeyChangeFnName: 'onChange' });
export const FormUpload = withField(Upload, { valueKey: 'fileList', valuePath: 'fileList', onKeyChangeFnName: 'onChange' });
export const FormTagInput = withField(TagInput);
export const FormPinCode = withField(PinCode);
